#!/usr/bin/with-contenv sh
# Usar el venv
export VIRTUAL_ENV=/opt/venv
export PATH="$VIRTUAL_ENV/bin:$PATH"

# Opcional: espera de red/variables
# s6-setuidgid nobody:users  # si quieres bajar privilegios

# Lanza tu script Python
exec python /app/huawei_mqtt_publisher.py